# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsubasa < Formula
  desc "Tiny, and simple Elasticsearch microservice to abstract searching objects!"
  homepage ""
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.1/tsubasa_0.3.1_Darwin_arm64.tar.gz"
      sha256 "09e4290e4b92989b4e14ebcb9c5d058ca8f135ddedea0732f7b4d7ca3711ac72"

      def install
        bin.install "tsubasa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.1/tsubasa_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "67f66aba36ce384b91770aced5b6531356191e4ec227b7f0df66cf98f9b1672f"

      def install
        bin.install "tsubasa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.1/tsubasa_0.3.1_linux_arm64.tar.gz"
      sha256 "392075c7275dfe9f4c47a62299004575d2d9ab0f2a7d3977a2d09bd6eef94238"

      def install
        bin.install "tsubasa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.1/tsubasa_0.3.1_linux_x86_64.tar.gz"
      sha256 "c2e7616d8650f825ab07d647a87979e9c7c4570f64f02a13d07b1affad72168f"

      def install
        bin.install "tsubasa"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.1/tsubasa_0.3.1_linux_armv6.tar.gz"
      sha256 "5c539c0a3bf57b6eed8590a6e1d647eadafc080e8c1b4bd5216b7dd6c297a2aa"

      def install
        bin.install "tsubasa"
      end
    end
  end
end
