# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsubasa < Formula
  desc "Tiny, and simple Elasticsearch microservice to abstract searching objects!"
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.0/tsubasa_0.3.0_Darwin_arm64.tar.gz"
      sha256 "8444fb1ad643ab3b6b32c0a0757f28f19de84ddab8fde6c4cb0b04ff19fc925b"

      def install
        bin.install "tsubasa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.0/tsubasa_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "cb3176c6d3477f0e80942d09a5bf7f4a6acc1900906645bdabd8239f7b5d7f97"

      def install
        bin.install "tsubasa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.0/tsubasa_0.3.0_linux_armv6.tar.gz"
      sha256 "1592cd2ddf4dd0d58f41c0a8eea4af33f3fd4332e1550c5d9e61a166820bd843"

      def install
        bin.install "tsubasa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.0/tsubasa_0.3.0_linux_arm64.tar.gz"
      sha256 "2c1c493102c185edb5dc9521c81e18171338781bfb0b7a29b88746a7b3cbe62d"

      def install
        bin.install "tsubasa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/auguwu/tsubasa/releases/download/v0.3.0/tsubasa_0.3.0_linux_x86_64.tar.gz"
      sha256 "cb2463811aa825fc525650338ec831f9cc2cb43a2a0a10c9006340d85297ebd9"

      def install
        bin.install "tsubasa"
      end
    end
  end
end
